### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by jason-tratta** [blackboxembedded/WunderLINQ-iOS#1]
Hey guys, 

Thanks for making the code open source, I can't wait to check this out on my bike.  I ran into a few small issues getting this to compile. 

1) It looks like the InfoPlist.strings is missing from the repo?  You can remove this from the target Copy Bundle Resources to compile successfully, however I haven't tested localization to see it it crashes. 

2) The "lightbulb" image asset needs to be renamed to "Lightbulb."  The app is currently crashing until this is changed.

**Comment by blackboxembedded** [comment]
Hi Jason,

> Thanks for making the code open source, I can't wait to check this out on my bike. I ran into a few small issues getting this to compile.

Your welcome! We are looking forward to seeing what folks come up with!

> 1. It looks like the InfoPlist.strings is missing from the repo?  You can remove this from the target Copy Bundle Resources to compile successfully, however I haven't tested localization to see it it crashes.

Hmm, they are there under each locale directory. For example https://github.com/blackboxembedded/WunderLINQ-iOS/blob/master/WunderLINQ/Base.lproj/InfoPlist.strings

What's weird is if a clone the repo it builds on my end.  

> 2. The "lightbulb" image asset needs to be renamed to "Lightbulb."  The app is currently crashing until this is changed.

I've fixed this, apparently, MacOS didn't "detect" the case change.

**Comment by jason-tratta** [comment]
It looks like the input files could be referring to another location on your dev computer and not in the GitHub version?  Here is one of the errors it throws until I remove it from the bundle. (sorry I should have mentioned this in the initial report) 

`error: Build input file cannot be found: '/Users/keithconger/Projects/iOS/WunderLINQ/WunderLINQ/sl.lproj/InfoPlist.strings' (in target 'WunderLINQ' from project 'WunderLINQ')`

**Comment by blackboxembedded** [comment]
> It looks like the input files could be referring to another location on your dev computer and not in the GitHub version? Here is one of the errors it throws until I remove it from the bundle. (sorry I should have mentioned this in the initial report)
> 
> `error: Build input file cannot be found: '/Users/keithconger/Projects/iOS/WunderLINQ/WunderLINQ/sl.lproj/InfoPlist.strings' (in target 'WunderLINQ' from project 'WunderLINQ')`

Thanks for the tip, let me see if I get a fix up.

**Comment by blackboxembedded** [comment]
OK, it should be fixed.  Let me know.

**Comment by jason-tratta** [comment]
That fixed the InfoPlist issue.  Thanks!

Just one small thing, the case calling for the lightbulb icon in the MainCollectionViewContoller is throwing an error.  It's just set to the old value, otherwise it runs "out of the box" now. 

` case 10:
            // Ambient Light
            icon = (UIImage(named: "Lightbulb")?.withRenderingMode(.alwaysTemplate))!
            if motorcycleData.ambientLight != nil {
                value = "\(motorcycleData.ambientLight!)"
            } else {
                value = NSLocalizedString("blank_field", comment: "")
            }`

Thanks again, 
Jason

**Comment by blackboxembedded** [comment]
Thanks, fixed that reference as well.

> That fixed the InfoPlist issue. Thanks!
> 
> Just one small thing, the case calling for the lightbulb icon in the MainCollectionViewContoller is throwing an error. It's just set to the old value, otherwise it runs "out of the box" now.
> 
> ` case 10: // Ambient Light icon = (UIImage(named: "Lightbulb")?.withRenderingMode(.alwaysTemplate))! if motorcycleData.ambientLight != nil { value = "\(motorcycleData.ambientLight!)" } else { value = NSLocalizedString("blank_field", comment: "") }`
> 
> Thanks again,
> Jason
