### ISSUE TITLE
Data screen enhancements

### ISSUE THREAD

**Issue by kpavey** [blackboxembedded/WunderLINQ-iOS#34]
Hi love the data screen in BBE but would like to see some simple potential enhancements. For instance:

**Fuel Range** - could it be green if above 80km, yellow between 80-40km and red below 40km? Perhaps add a fuel bowser graphic behind it? I'm thinking colouring the background rather than the number itself so it remains readable in all light conditions
**Voltage** - could it be green above 14.0V, yellow between 13-14V and red below 13V? Perhaps add a voltage gauge behind it?
**Tyre pressures** - can the R/Y/G be configurable, but default to 36/42psi green, yellow 4 psi lower and red anything below that? Perhaps add a tyre pic behind it
**Ambient temperature** - below 10C light blue, 10-20 yellow, 20-30 orange, above 30 red? And/or perhaps a little thermometer graphic behind it?
Could **Altitude** have a little mountain graphic behind it?
Could **GPS Speed** have a little speedo graphic behind it? (And Average Speed)
I guess you get the idea. The idea is to make the items a little more readable at a glance and draw your attention to values which may need attention. The tripping point values are just suggestions. Thanks for considering. Great device!
Cheers Kendrick

**Comment by blackboxembedded** [comment]
Implemented the color changes to value text and icons.
