### ISSUE TITLE
WunderLINQ app close on iPad

### ISSUE THREAD

**Issue by Denis66625** [blackboxembedded/WunderLINQ-iOS#68]
The WunderLINQ app close automatically on my iPad with IOS15

**Comment by blackboxembedded** [comment]
@Denis66625 can you tell me which iPad variant you have?  I want to try to replicate it in a simulator.  Just to confirm the app crashes at launch?

**Comment by Denis66625** [comment]
Hi,

I have an IPad mini 6 (2021). Last version of IPadOS (15.2.1)
You can see the app crash in the video (attachement)

Thanks,
Denis

**Comment by blackboxembedded** [comment]
Hi @Denis66625 

Could you send the video to support@blackboxembedded.com?  GitHub removed your attachment.

Thanks

**Comment by blackboxembedded** [comment]
Attach video.
https://user-images.githubusercontent.com/64652300/151456169-1dcd362d-62ab-4ac8-872e-18e77dd80285.mov

@Denis66625 can you test the next beta build 2.0.7build?   It hopefully resolves your crash.

**Comment by blackboxembedded** [comment]
I believe this is fixed.

**Comment by blackboxembedded** [comment]
Log of issu
[wunderlinq.log](https://github.com/blackboxembedded/WunderLINQ-iOS/files/9263306/wunderlinq.log)
e
