### ISSUE TITLE
App settings Highlight color crash

### ISSUE THREAD

**Issue by barisertgrul** [blackboxembedded/WunderLINQ-iOS#69]
- open app settings while not connected to the hardware
- click highlight color
- app crashes

tested on: ios 15.2 / iphone 12
 also changing night mode crashes the app

**Comment by blackboxembedded** [comment]
I can confirm that I can reproduce on my end.

**Comment by blackboxembedded** [comment]
Resolved, 2a18a8b601009bc6a54ff5221f12f8ff0077ccad
